sudo: required
language: python
services:
- docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libusb-1.0-0-dev
      - libudev-dev
      - libsecp256k1-0
matrix:
  include:
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode8
  - os: linux
    python: "3.6"
    dist: xenial
  - os: linux
    env: ELECTRUM_MAINNET=true
    python: "3.7"
    dist: xenial
  - if: tag =~ .+
    os: linux
    env: ELECTRUM_MAINNET=false
    python: "3.7"
    dist: xenial
before_install:
- source contrib/terracoin/travis/electrum_trc_version_env.sh
- echo electrum-trc version is $TERRACOIN_ELECTRUM_VERSION
- mkdir -p build && cp contrib/terracoin/travis/* ./build/
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/before_install-osx.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox; pip install tox-travis;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]];then
      tox;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
     travis_wait 30 ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  edge: true
  api_key:
    secure: Ai8/85+KOOyuciaR4Z0zfczjy4GzcWNCus/qWmG1ix9nLbe4yt95anmGvhNrmJpNbBnKmYxiPtJuHAdIknRvDKDFAlSi1RPaAmkqSPMbLMq2MkyvOQne75yhkffFTtIONj9NUafqDIeWKJbD75o3ucLwMzwM8acbAkwrX3D15RRoJsoghU7acQXhqjzCNlLg+oI/nAw/SkXpBfDOTwVuT1PAJ+4jjF9WWKTrkvrcR7A5+kmCmi0RjEj7Ov9DfZVAt8IvZNiTM5sJeGv9h88N5oHAYhXa/66bpyq7vtqEcd548hR3fXXgtgTpToMrmzLqHjM6QHJF5VQQiVlFhvQCHuW/Vl+Mt9+YxUIzctvi1rUS3bsmXZwAcHEmH9+3oVcSR4/hxNYkMDAettw2AfcmQEwj4zrdtE28xOtkeRsE/od2erMBbxIzpTAyupo4N7D7a097q5NvR2kWa7r9F+8A9Fq8iPb7fLBekU6ny2Qq6s4FR/+7dV8vd15rLh2OyMUOU+Vyp9S/Lfzl++Q2q4pDHfITvCHLPf9HE7Cf4ZzSbxyeDvzX3hbKr0QGzqyrMfffKs41ACJSHJKd6Q0DtPofObEOYBJnEYeLhU/24d7sZNyORAdwE4RYkviBC2tbokJKF5TLuKxTTzH1POt8eWmy+z7GOEiP1CCi1/dAsWoFtns=
  file:
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION-macosx.dmg
  on:
    repo: terracoin/electrum-trc
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  edge: true
  api_key:
    secure: Ai8/85+KOOyuciaR4Z0zfczjy4GzcWNCus/qWmG1ix9nLbe4yt95anmGvhNrmJpNbBnKmYxiPtJuHAdIknRvDKDFAlSi1RPaAmkqSPMbLMq2MkyvOQne75yhkffFTtIONj9NUafqDIeWKJbD75o3ucLwMzwM8acbAkwrX3D15RRoJsoghU7acQXhqjzCNlLg+oI/nAw/SkXpBfDOTwVuT1PAJ+4jjF9WWKTrkvrcR7A5+kmCmi0RjEj7Ov9DfZVAt8IvZNiTM5sJeGv9h88N5oHAYhXa/66bpyq7vtqEcd548hR3fXXgtgTpToMrmzLqHjM6QHJF5VQQiVlFhvQCHuW/Vl+Mt9+YxUIzctvi1rUS3bsmXZwAcHEmH9+3oVcSR4/hxNYkMDAettw2AfcmQEwj4zrdtE28xOtkeRsE/od2erMBbxIzpTAyupo4N7D7a097q5NvR2kWa7r9F+8A9Fq8iPb7fLBekU6ny2Qq6s4FR/+7dV8vd15rLh2OyMUOU+Vyp9S/Lfzl++Q2q4pDHfITvCHLPf9HE7Cf4ZzSbxyeDvzX3hbKr0QGzqyrMfffKs41ACJSHJKd6Q0DtPofObEOYBJnEYeLhU/24d7sZNyORAdwE4RYkviBC2tbokJKF5TLuKxTTzH1POt8eWmy+z7GOEiP1CCi1/dAsWoFtns=
  file:
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION.tar.gz
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION.zip
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION-x86_64.AppImage
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION-setup-win32.exe
  - build/electrum-trc/dist/Terracoin-Electrum-$TERRACOIN_ELECTRUM_VERSION-setup-win64.exe
  - build/electrum-trc/bin/Electrum_TRC-$TERRACOIN_ELECTRUM_APK_VERSION-release-unsigned.apk
  - build/electrum-trc/bin/Electrum_TRC_Testnet-$TRC_ELECTRUM_APK_VERSION-release-unsigned.apk
  on:
    repo: terracoin/electrum-trc
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
